### ISSUE TITLE
Suggestion: Enable preview build on pull requests

### ISSUE THREAD

**Issue by rffontenelle** [pypa/packaging.python.org#1158]
Enabling this feature in p.p.o readthedocs projects makes a preview documentation be available in the pull requests. See https://docs.readthedocs.io/en/stable/pull-requests.html for instructions on how to set it up and more info.

How it looks in pull requests:
![github-build-status-reporting](https://user-images.githubusercontent.com/1571783/197539983-d9e8fb8f-0d86-4aff-b17c-4d2b2098b4b6.gif)

**Comment by rffontenelle** [comment]
@bhrutledge ah, my bad. I thought I didn't see it enabled in here. Thanks for the quick reply

**Comment by webknjaz** [comment]
@rffontenelle would it be useful to also enable the pt-BR instance there?

**Comment by rffontenelle** [comment]
@webknjaz I'm not sure how readthedocs would handle more than language doc in same pull request but I guess we can try. I'm going to enable pt-BR. Can you enable it in another language with activity, so we can see it in the pull request?

**Comment by webknjaz** [comment]
@rffontenelle I just realized that it'd be pointless because we don't store any localization files in the main branch. RTD would probably be able to build PRs to the translation branch. And the only PRs created against it are the weblate ones. Other PRs will likely get failed statuses or no status update at all (which should be fine but not very useful). So it seems that to get proper PR builds, we'd need to build own automation...

**Comment by rffontenelle** [comment]
@webknjaz I see. I envision CI workflow triggered for each language that builds and report the same issues as the English docs, and that is triggered only when a push or pull_request happens for that(those) language(s). First I'll finish my PR of Enable build for translated docs, then I'll figure it out.
