### ISSUE TITLE
Add changelogs to all standards

### ISSUE THREAD

**Issue by encukou** [pypa/packaging.python.org#1203]
It would be good to add a “History” section to all [PyPA specifications](https://packaging.python.org/en/latest/specifications/), [like the one in `direct-url`](https://packaging.python.org/en/latest/specifications/direct-url/#history).
Even with a single entry, the section is useful -- to set expectations for future updates.
Please add dates if the spec isn't versioned in another way.
See [discussion on Discourse](https://discuss.python.org/t/1659/28).

**Comment by jeanas** [comment]
I agree that dates throughout would be useful, since they may be relevant to users when they wonder how recent the tool must be to support feature X or Y.

IMHO, we don't need the PEP approval messages because they're already recorded on the PEP's page (or should be); OTOH, links to discussions other than PEPs are useful.
