### ISSUE TITLE
Common use for build numbers is being mischaracterized

### ISSUE THREAD

**Issue by gh-andre** [pypa/packaging.python.org#1289]
This paragraph in the section for `build tag` on this page says:

https://packaging.python.org/en/latest/specifications/binary-distribution-format/#file-name-convention

> A common use-case for build numbers is rebuilding a binary distribution due to a change in the build environment, like when using the manylinux image to build distributions using pre-release CPython versions.

Build numbers have been around for a while and rebuilding a package for a different distribution isn't what they are intended for, but instead they are intended for tracking build maturity while working towards an upcoming package release. That is, a CI pipeline would routinely build packages with the same version and different build numbers, which will be tested and exactly one of them, which passed all the tests, will be released.

The following warning correctly identifies that a build number alone shouldn't be used for patch releases, but provides little insight into how patch releases should be approached, which is to bump the patch level component of the version, which automatically restarts build numbers, just by the virtue of having a new release.

For example, one can have these candidate packages for an upcoming release `1.2.0` built internally by a CI pipeline and tested, like shown in this sequence.

`abc-1.2.0-24.main-py3-none-any.whl` => failed testing, discarded
`abc-1.2.0-25.main-py3-none-any.whl` => failed testing, discarded
`abc-1.2.0-26.main-py3-none-any.whl` => all tests passed

The last package that passed all the tests can be released as version `1.2.0`. The build number `26` is just informative and will never be different for a publicly released version. It may even be dropped from the public package name because internally it is always tracked as a built `26` of release `1.2.0`.

If a security issue is identified in the package of `1.2.0`, then a new version will be released using the same logic, with a bump of the patch component, like this.

`abc-1.2.1-1.main-py3-none-any.whl` => failed testing, discarded
`abc-1.2.1-2.main-py3-none-any.whl` => all tests passed

, and a security fix will be released as version `1.2.1`. Same as before for the build number - it's `2` and will never change for version `1.2.1`.

What the quoted paragraph describes is more of a _local version_ described in [PEP 440](https://peps.python.org/pep-0440/#local-version-identifiers), which is intended for rebuilding the source of a particular version by downstream package maintainers.

**Comment by webknjaz** [comment]
@gh-andre it sounds like you misinterpreted the term "distribution" as a "Linux [downstream] distribution" and not a Python distribution package. Is that right? Plz confirm.

**Comment by webknjaz** [comment]
cc @sethmlarson do you think we could improve phrasing and maybe link the glossary term to address this?

**Comment by gh-andre** [comment]
> it sounds like you misinterpreted the term "distribution" as a "Linux [downstream] distribution" and not a Python distribution package. Is that right? Plz confirm.

In my post "distribution" refers to the "binary distribution" (i.e. _wheel_) carrying build numbers, which are not described as a build maturity tracking mechanism, but rather as a way to release something publicly with the same version and a different build number, which should not ever be the case (yes, the warning in red discourages some of that, but in confusing terms). 

As an example, I can have a CI pipeline publish into AWS CodeArtifact candidate wheel packages with the same version and different build numbers (CodeArtifact calls those _assets_), so my test suite can pick up the latest one from my dev package repo. The wheel package that passes all the tests will be released, which will be the only build number ever visible publicly for a particular version (i.e. PyPi will never see same version and different build numbers).

**Comment by webknjaz** [comment]
Interesting.. I was thinking along the lines of compiling a wheel against a CPython alpha/beta/rc but then, rebuilding under final once it's available. In that case, PyPI would see several build numbers of the same wheel.

**Comment by gh-andre** [comment]
It would be hard to maintain release notes for such releases because release notes are supposed to be written for a version, not a build number. Builds numbers are supposed to be an internal tool to track build maturity for a specific release. 

I would also note that the way you mentioned alpha, beta, etc, those are actually public releases, not internal release candidates. This is a subtle, but important point - an alpha release would be consumed by users understanding that the release lacks features and stability, but other than that, it's just a public release, which should still go through the same sequence of build numbers internally, until one CI package passed all the tests acceptable for an alpha release and will be released with the alpha designator in the version component of the wheel package, not as multiple build numbers.

**Comment by sethmlarson** [comment]
@gh-andre Thanks for opening this and sharing your concern, your use-case for build numbers seems more sensible to me (ie build numbers are used but each release only has one unique build number). Did you want to submit a PR with a proposed update to the prose?

**Comment by gh-andre** [comment]
@sethmlarson Thank you for your thoughts.

One clarification I should add is that the build number would be unique per package tuple, including `(version, python-tag, abi-tag, platform-tag)` not just a version. This is because one pipeline run may have a matrix build of the same source and may produce a mix of flavors of the package with various build numbers, including same, like this:

* `abc-1.2.0-96.main-py27-none-any.whl`
* `abc-1.2.0-96.main-cp3-someabi-win32.whl`
* `abc-1.2.0-32.main-cp3-otherabi-win32.whl`
* `abc-1.2.0-96.main-cp3-someabi-linux_x86_64.whl`

Not sure about the local version - sounds like if downstream package maintainers build a new package, their own build numbers would replace or ignore upstream build numbers, depending on how they run their builds.

Problem is, many Python build tools adopt the `npm` way and it's quite hard to produce Python packages with proper build numbers because many build backends lack support for build numbers (e.g. setup tools has the option, but it misbehaves, making it impossible to generate build numbers. Other tools don't have support for build numbers at all).

Given that `npm` doesn't differentiate between CI package repositories (which should accept packages different only in build metadata) and public repositories (which must not, as there's only one build that passed all tests and can be released) and just drops build metadata, many mistake this for a new better way to package and start bumping version components instead of build numbers in CI builds.

The way I worked it around is that `wheel` does it right, so I generate a package with a build backend and then run it through `wheel tags --build` to inject the build number. Not sure if this would work for everyone.

So, my hope is that if the binary format spec defines build numbers and their purpose more elaborately, build backends would eventually add functionality to generate build numbers. However, because there are limited ways to actually generate them, this may require more finesse in describing it than I would provide.

Given all this, let me know if you still want me to take a stab at a PR.

**Comment by dstufft** [comment]
Note: The spec doesn't really have an opinion on what exactly you use build numbers for, it describes how they're interpreted and gives one use case for them. The use case could be dropped completely (we don't list a use case for any other part of the spec afaik) or we could add another use case.

In either case, I don't believe it changes the spec itself, so either change should be fine.

**Comment by gh-andre** [comment]
@dstufft I agree that implementation-specific use cases and examples don't belong in a spec, such as references to matrix builds, etc. However, a spec should provide intended purpose for various bits, just like it says in some places today, like _"Archivers are encouraged to..."_.

In this case, the intended purpose is misstated in _A common case where a distribution would need to referenced externally is when resolving a security vulnerability._, which should never be the case, as security vulnerabilities should be addressed in a patch bump, so most auto-update patterns would pick them up.

My suggestion would be to say something along these lines:

_Build numbers are intended to track build maturity while working towards a versioned release and shall be resolved for the same version and different build numbers in dev package repositories as described above. A public release shall have a unique build number for a version/python/abi/platform tuple. Any additional changes in a public release, such as security patches, shall be tracked via changes in version components._

**Comment by henryiii** [comment]
The key feature of build numbers is that you can upload a binary with a new build number. One proposed solution to shipping Python 3.X Beta wheels on PyPI was that if there was an ABI change, a package could be rebuilt with a "1" build number using the newer Python 3.X beta/RC, and just the Python 3.X wheel would need to be shipped. It's exactly the same code, so there's no need to make an entirely new release.

For the case above (which I haven't seen any major packages use like NumPy), can't you just retag it without the build number after it passes, so user's won't see how many times the CI failed before passing?

**Comment by gh-andre** [comment]
@henryiii Thanks for your insights.

With regards to alpha and beta releases, those are regular releases, really, just made available for general public and with assumed lower quality and/or fewer features. Other than that, they still should get a bump in a release version every time an updated version is released, such as `beta.1`, `beta.2`, etc., and still need build numbers while they are being prepared for a release. 

There is really no use case where one would release same version and different build numbers publicly. Build numbers is a tool for preparing a package for a release, never a mechanism for tracking release fixes and features in release notes. Granted, people do it nowadays, but what it really means is that they just replaced a release version with a release version + build number in their release notes. Might as well just incorporate build number into the version, as the 4th component. Although in this case their releases will not have monotonically increasing version sequences (e.g. `1.2.3.217` and `1.2.3.302` one after another).

**Comment by henryiii** [comment]
Sorry, I didn't mean beta releases of the wheel project's software. I meant beta releases of CPython. Here's an example:

1. CPython 3.13.0b1 is released. It is not ABI stable yet (that happens on the last beta).
2. NumPy makes a 1.27.0 release with binaries for all versions and OSs, including the 3.13.0b1 CPython release. This is what some steering council members are publicly asking projects to do. (Pick a smaller project here if you want, just picking NumPy for simplicity).
3. CPython 3.13.0b2 is released with a breaking change to the ABI.
4. The 3.13 wheels for NumPy 1.27.0 are now broken on CPython 3.13.0b2 and future betas, RCs, and most importantly, the final release.
5. NumPy produces new 3.13 wheels, _without a single code change_, of 1.27.0. They bump the build number (with `pip -m wheel tags --build-number 1 <old-wheels>`). And upload the new wheels just for CPython 3.13.

They didn't have to make a new release (1.27.0 was fine). Most projects don't want to or can't make emergency releases for one platform. They didn't have to upload identical wheels for the other 60 or so possible binary wheels. They didn't need to double their storage space - even 10 MB x 60 is 600 MB per release. And the fact that old lock files and old downloads have the old build doesn't matter, since anything you do with CPython betas and RCs is known to be temporary. New solves and lock file include the new one.

That's what a new build is, no code changes, just the underlying platform has updated. And helping users support that is nice (at least if we want to push users making wheels as early as possible in the release process - cibuildwheel's recommendation is RC 1, when it's ABI stable).

(That's the idea, anyway, I don't think it's happened yet. But it's at the core of the suggestion for building wheels during betas instead of RCs, IMO.)

In theory, you could also do this if anything changed in the underlying system (outside your package), and you needed to upload a new binary but only for one OS or one CPython version, etc.

**Comment by gh-andre** [comment]
@henryiii Thanks for the example. I see what you mean. 

As a general (non-Python) case, what you are describing is happening for projects that are packaged downstream, so they may release another package of the same upstream software built in a different way (e.g. updated dependencies, different compile options, patched upstream source for a bug, etc). These are typically managed with package revisions - same upstream version, different package (e.g. `rpm`).

Some packages don't support package revisions and they have to be piggybacked on some other component. Nuget is a good example - the 4th version component may be used by packagers for this purpose and is completely detached from the original software release notes. Others don't support them at all, like `npm`.

For Python, it appears that [Local Version](https://peps.python.org/pep-0440/#local-version-identifiers) is intended for downstream packagers to achieve what you are describing. There's no good (or any) support for these in Python build tools, so it may be my wishful thinking, but at the requirement level, local versions would work well for what you are describing.

With regards to build numbers, I think it would not be a good idea to use them for this purpose either, simply because one typically wants to attach release notes to a version, not to a build number. In your example, if you want to describe ABI compatibility notes for 3.13.0b2, the release notes would have to be attached to a build number, which lacks version quality attributes, such as sequential components (e.g. did you miss a package between builds `12.ab93eb8` and `35.d520418`?) or the level of change (i.e. in Semantic Versioning sense).

**Comment by henryiii** [comment]
Local versions are _not_ for distribution to PyPI, the link you sent specifically says that. They are for internal (local) things like different environments or build configurations, which are not supported on PyPI. It also does not allow you to ship a new wheel, it forces a new release of all your wheels. You might as well use an extra digit, for example.

We do not report the exact build environment in changelogs. A built number of 1 means the package was rebuilt once. Changelogs talk about changes in the _source_, and rebuilding a wheel does not change the source. Downstream packagers using the SDist don't care since they have their own builds. PyPI is _also_ a binary distribution platform, and binary distribution platforms sometimes need to rebuild. While it's more likely than most platforms to have artifacts supplied by upstream, I know of several projects where the binary wheel builds are not in control of the upstream at all. Also, a private index might need rebuilds, for example, doesn't need to be PyPI - it's just a mechanism to allow a package to be rebuilt and put on an index alongside wheels _of the same version_. Conda, homebrew, and most other binary distribution platforms use build number bumps - people assume that a higher build number means a rebuild was needed.

I don't see why you'd ever want to ship a single binary to PyPI but have an arbitrary build number attached to it based on the number of times you tried and failed to build it. That's not interesting or relevant information for the normal consumer, and now they have to include a uncomputable number in the filename instead of being able to construct it from the name, version, and platform. I'm not saying you can't, just I don't see why downstream users would care. Personally, if I had failing builds and wanted to track them with build numbers, I'd normalize everything to no build number before publishing. If you do that, you could ignore changing the internal metadata entirely and just put the files in numbered folders and get the same effect. However, being able to ship a single new binary to an index is an important[^1] feature to have for cases like described above unavailable any other way.

PyPI (for security reasons, mostly because not enough people check hashes) doesn't allow reuploading the same wheel. FYI, CPython has rebuilt and swapped out binaries before when they needed to update just one binary, they don't follow the PyPI rules. :(

[^1]: As in, theoretically important, not that I see people using it much or at all. But useful if we want to ask people to support CPython releases sooner, which some people really want.

**Comment by henryiii** [comment]
FYI, I'm not at all against mention this use case, by the way, I'm just against removing the current use case description, which is exactly what I've been told this would be useful for. Personally, I haven't ever used it for either - I've always had to change at least one thing in the source, which means a changelog and a new release. ;)

**Comment by henryiii** [comment]
FYI, I just ran into a package using a build number to upload fixed arch builds:

https://pypi.org/project/black/22.10.0/#files

I ran into it because it was causing an issue in producing the name in pipx's tests, the package name was being computed as `black-22.10.0==1fixedarch` (which is wrong!), but it's an example of this being used in practice.

**Comment by gh-andre** [comment]
@henryiii 

> I'm just against removing the current use case description, which is exactly what I've been told this would be useful for.

Well, what the phrasing on that docs page is effectively saying is that build numbers should be treated as package revisions and not as they have been used historically, which is a unique build metadata sequence for every CI pipeline build.

If that's the case, then perhaps the spec should clarify that CI pipelines should not use this component for tracking what historically was considered as a build number, but rather treat it as a package revision. Combining these two meanings only creates confusion, because traditional build numbers would be used for preparing _any_ release, including those that produce package revisions.

**Comment by gh-andre** [comment]
This revision of the docs is starting to take the toll on implementations in that people misinterpret what build numbers are supposed to be used for. This one, for example, just ditches build numbers altogether and instead provides a way to set up a local version, which is intended for a completely different purpose.

https://github.com/python-poetry/poetry/issues/1208#issuecomment-2016274337

**Comment by henryiii** [comment]
You are welcome to propose updating it to this use case, I just was against removing the current use case. The Poetry thing seems wrong at first glance - local versions are not supported on PyPI so they can't be equivalent.

**Comment by gh-andre** [comment]
@henryiii The common use case for build numbers is to distinguish multiple builds created by the build pipeline towards the same version, _one of which_ will be released when it checks all the boxes for the intended version and that's the one that reaches a public repository.

What is currently described as a common case, is more of a compensation for the lack of package revisions in Python, where one takes some upstream source and rebuilds it with different flags, for example. This problem is really for the PEP folks to figure out and propose an updated nomenclature, but until this happens, using build numbers for this purpose is a mere workaround and characterizing it as a common use case will mislead people.

**Comment by henryiii** [comment]
> The common use case

I strongly object to this repeated language. Looking at every package on PyPI, I can see 17,126 wheels with build numbers. I see a lot of examples of reuploads, such as Pillow 8.3.1, 9.0.1, and 9.4.0, numpy 1.13.3 on Windows, quite a few for numba, cryptography 1.7.2 on macOS for Python 2.6, etc.

I don't think building the same wheel in multiple pipelines then only releasing one passing one is all that "common". It also doesn't _require_ build numbers (tags); the end user doesn't need to know which build pipeline succeeded, so it could be tracked internally instead. While re-uploading a broken build of just some wheels _requires_ build numbers. 

>More of a compensation for the lack of package revisions in Python

It's used to reupload a broken wheel build of a subset of binaries when you have more than one. For example, `black-22.10.0` was broken on macOS, so `black-22.10.0-1fixedarch` was reuploaded, just on macOS. This is important for large packages that don't want to rerelease a new version when they are only making a new build of some binaries. That's what "build number" means, and that's why there are sorting rules and the requirement that it start with a number. FYI, CPython itself reuploads broken builds instead of making a new release - without a "build number" since they aren't wheels, so the hash of some of the CPython downloads can change. Been bitten by that before, IIRC Windows 3.11.0 got reuploaded. Much prefer build numbers!

I think listing multiple common use cases is fine. Replacing a valid use that packages are actively using with what you consider "common" isn't.

And Poetry doesn't really like binary builds; they aren't handled very well in the solver (it assumes all wheels have the same requirements, which isn't guaranteed), they don't support making binary builds very well (they get things like the tags wrong when cross-compiling, since it's just hacked in by plugins and not fully supported in core), etc, and Poetry hasn't been adopting PEPs very quickly, so not that big of a deal or that surprised that they aren't supporting build numbers.

**Comment by henryiii** [comment]
If I were you, I’d start by proposing an update to https://packaging.python.org/en/latest/specifications/binary-distribution-format/#binary-distribution-format to clarify that. That’s the working that caused the Poetry decision. That working currently excludes your use case.

**Comment by gh-andre** [comment]
Not sure you see what I'm describing. How do you identify packages in your CI/CD pipelines?

> It also doesn't require build numbers (tags); the end user doesn't need to know which build pipeline succeeded, so it could be tracked internally instead. 

I didn't say the end user needs to know that. On the contrary, the end user only cares about versions. A build number is what one uses preparing a release, not after the release.

Having it in the package name merely makes it easier identify these packages, as opposed to tracking it in accompanying files or via something like integration folders, and to avoid potential failures introduced while stripping build tags with something like `wheel`.

> While re-uploading a broken build of just some wheels requires build numbers.

One of the main advantages of using build numbers in the package name is that you always verify the very package you built, without repackaging, so those who use build numbers should not run into broken builds with released packages simply because they wouldn't pass the tests.

> This is important for large packages that don't want to rerelease a new version when they are only making a new build of some binaries

That's where package revisions would come in handy, indeed, but since there's no official nomenclature for this, people use workaround and it seems that using build numbers for this is one of the examples.

Unrelated to Python, but I do this with Nuget packages quite often - sometimes I build 3rd-party source with different compiler flags and release it as some upstream version, and add a fake package revision expressed as the 4th version component (Nuget doesn't support package revisions either). So, I hear you on this point, even though I would probably use something else for this, like adding a version component because versions is one one expects in release notes and also because I would need build numbers to build and test that package.

> If I were you, I’d start by proposing an update

If I was after package revisions, as you brought up on a couple of occasions, I would, but I'm just trying to describe that build numbers are intended for preparing a release and using them as a workaround for package revisions, such as security fixes, will likely confuse people about the intended purpose of build numbers.

**Comment by henryiii** [comment]
Unless you wrote the spec, I would not describe what build numbers were _intended_ to do. I've argued similarly before (about Python-Requires), and had one of the authors of the original PEP tell me I was wrong. Even if you did write the spec, the original intent isn't necessarily how the feature is used in practice. Instead, I'd look at how they are implemented and used. And if they were never intended to be used to upload new builds of some wheels, why are they required to start with a number, have clear sorting rules, and multiples are allowed on PyPI? The original specs don't indicate much intent at all.

It's important to realize that not everyone using Python uses it the way you do (this is true for anyone, including me). Python has a very diverse community in every sense of the word. Many people have very different pipelines than you describe. "build maturity" is a foreign concept to packages like numpy, which don't release if tests don't pass and if all builds don't succeed.

"Build number" as a term may be used in third party packagers to indicate build revisions, usually due to rebuilds or recipe changes. Conda-forge calls this a build number. Homebrew calls it the revision.

In Python, there are three ways to make a revision. If the code changes, or if a user is supposed to get a new version if they already downloaded it, the version should be bumped, possibly fourth component, but it has to be a real bump. If only metadata changes like a URL on the homepage (pip won't consider it an upgrade worth downloading), then a `.postN` release can be used. And if a binary needs to be rebuilt for only some platforms without source code changes, a build number can be used. This is the _only_ way to do this without reuploading the entire set of wheels; PyPI doesn't allow re-uploads of existing binaries and you can't upload partial distributions. And the storage space is limited. And people using Linux don't care if you had to rebuild macOS because the Apple Silicon wheels were accidentally Intel inside. And it's not a new version, no source has changed, it is just a new _build_ of one or more wheels. Notice I haven't talked about intent - this is just implementation and what is allowed. IMO, we don't need a forth way, this covers enough. Though I'd like a way to patch metadata :).

I've never said (at least I hope I didn't, it's a long thread now!) that you didn't have _a_ use for build numbers, I just objected to you saying it is "the intended use". Your use sounds fine, though it does seem to me you could manage it without this specific feature if you had to - I could see someone suggesting build numbers be removed (at least from PyPI) if this was "the intended use". I'd be happy to see a proposed update that includes this use case, as long as it doesn't frame it as "the way" they should be used or something.

If you want this updated, you need to make PR(s) that take into account the discussion. I think there are several things that could be done:

* The warning is technically correct, but seem to have mislead some readers into thinking that build numbers are not recommended, when instead it is saying that "new distributions" (that is, a source code change) should not just bump the build number.
* A second use case could be added saying "build numbers can also be used to track internal pipelines, though if this is the case, a tool like `wheel tags --build ""` can be optionally used to strip them from the final upload to avoid exposing internal complexity to the users". Something like that?

FWIW, I don't think Poetry would care about this second use case, as they don't do binary builds, and it's not "required". If it was stated better, they _might_ care about the first case, but I'd still guess not. In _either_ use case, you can still use `wheel tags` to add the build number if you needed it for some reason.

**Comment by gh-andre** [comment]
@henryiii 

> Many people have very different pipelines than you describe. "build maturity" is a foreign concept to packages like numpy, which don't release if tests don't pass and if all builds don't succeed.

Feels like we are still not talking about the same thing. The way you describe `numpy` is exactly what build maturity is supposed to accomplish - you don't release a package unless it has all the features you want and all tests pass. 

Build maturity merely describes how a package transitions from the previous version to the upcoming one, as new features are added and bugs are fixed. No one does it in one build and every release goes through this process, however they call it.

> I just objected to you saying it is "the intended use".

It's called a "build tag" in the spec - a unique sequence associated with a specific build. Hence the intended use. The meaning one puts on that build tag once they have a package is all the variations of uses you describe. 

If you instead are referring to my saying that only one build number for a given version/Python/platform/ABI should get out of development, I do think it's a good practice because people expect release notes associated with versions/etc, but I can see someone releasing a different build tag under the same version/etc tuple. In this sense it's like I said that the intended use for cars is to transport people/cargo on paved roads, but then again, there are mining dump trucks out there. Perhaps I should've been more careful with the term "intended", since I cannot read minds of spec writers.

> The warning is technically correct

The warning is one of the uses of a build tag and specifying just one of them in the spec tips the scale towards this specific use. Removing this warning altogether and leaving it to users to interpret the spec would be less misleading.

Ok, I'm clearly not being successful in communicating why this warning is misleading, and it's a long thread indeed, so I will close it. Thank you for your insights.
