### ISSUE TITLE
__init__ should not be empty

### ISSUE THREAD

**Issue by jhlopezm** [pypa/packaging.python.org#1292]
In the webpage: https://packaging.python.org/en/latest/tutorials/packaging-projects/  was stated the following:
"__init__.py is required to import the directory as a package, and should be empty."

It did not work for me. Instead, when I wrote my methods in the __init__ file as before then it worked.

**Comment by sinoroc** [comment]
I guess it could/should read "_can be empty._"

I would really avoid suggesting that `__init__.py` can be omitted entirely, at least not without giving more details and warnings. As far as I understood it is not that straightforward. The fact that Python can import a directory without `__init__.py` as if it were a normal importable package is kind of like a coincidence (maybe an implementation detail even). Some details gathered here: https://stackoverflow.com/a/61504665

**Comment by henryiii** [comment]
Namespace packages are complicated and have some drawbacks. They exist to allow a package to be spread out on the filesystem, which is in practice AFAIK pretty rare. But agree this should say "can" not "should"!

**Comment by henryiii** [comment]
Ahh, I think this is another issue of this being a tutorial but treated like a guide. Following this tutorial, yes, it should be empty.

And "`__init__.py` is required to import the directory as a package" is technically correct, since it will be imported as a namespace package otherwise, but maybe adding the word "normal" would help in case someone notices it still imports without it.

**Comment by henryiii** [comment]
A namespace package is functionally different from a regular package. Some tools can't handle namespace packages. Paths work differently for namespace packages, since a namespace package could span multiple physical directories. All directories are valid namespace packages, even if they were never intended to be a package. IMO, namespace packages should be someone that someone who knows what they are doing can use, but normal users should avoid them.

Adding the word "regular" here wouldn't hurt, and would make it more technically correct, though.

**Comment by webknjaz** [comment]
> They exist to allow a package to be spread out on the filesystem, which is in practice AFAIK pretty rare.

Not at all. Some projects use this to namespace related things. "Rare" is depends on the ecosystem, I guess. For example, there's `backports`, `jaraco`, `sphinxcontrib` and `zope`, just off the top of my head. They are typically installed into the same directory layout under site-packages. Yet, the case of such importable packages spread across the file system is not typical for Python package distributions, but rather to the apps deployment side of things.

**Comment by sinoroc** [comment]
Have you all read this one? https://stackoverflow.com/a/62992832

**Comment by abravalheri** [comment]
> Have you all read this one? https://stackoverflow.com/a/62992832

I am not so sure about the reply's analysis of nesting namespaces inside regular packages. I remember testing different circumstances and finding some combinations that work (e.g. the "first distribution"'s parent package  contains `__init__.py`, but the "second distribution" leaves out all `__init__.py`); which can come in handy for plugin systems... (But my memory might be playing games, so it would be important to run the tests again).

The PEP that introduced implicit namespaces does intentionally equate them to regular packages and states that it is just a different way of implementing packages. So, at the end of the day, the decision of using namespaces (or not) comes to:

- tooling support
- the desire of leaving packages (or parts of packages) open for extension. 
- personal preference and idiosyncrasies
