### ISSUE TITLE
Add build backend and build frontend to the glossary

### ISSUE THREAD

**Issue by sinoroc** [pypa/packaging.python.org#1327]
I believe the terms "build frontend" and "build backend" should be defined in the glossary.

**Comment by sinoroc** [comment]
https://english.stackexchange.com/a/132325

There seems to be a consensus towards "front end (noun)" and "front-end (adjective)".

**Comment by zooba** [comment]
I think the space-less version have enough precedence that we should use them (certainly we're pretty good about "backend", and while "frontend" looks weird to my eyes, I'm not massively offended by it).

e.g. https://en.wikipedia.org/wiki/Frontend_and_backend

The adjective forms get the hyphen, but mostly we use the noun form (and possessive - "backend's documentation" rather than "back-end documentation").
