### ISSUE TITLE
Appveyor without appveyor.yml

### ISSUE THREAD

**Issue by jayvdb** [pypa/packaging.python.org#155]
Sometimes you want to do a Win32 build/package of a project, without adding appveyor.yml , and even without install.ps1 and run_with_compiler.cmd (e.g. non-Windows programmers who despise having such junk in their repo.)

I think it would be helpful to also show how this can be done.

As an example of doing it with appveyor.yml , but without install.ps1 and run_with_compiler.cmd , see https://gerrit.wikimedia.org/r/#/c/208957/

To do it without appveyor.yml, which is even more flexible also, set up the Appveyor project using their 'GUI' to do the install PS block, environment matrix, and test script.  This allows for rapid changes to the build matrix for example, without needing to push a new version of appveyor.yml into a repo (which will also trigger useless Travis CI builds, etc, etc)

If it is likely to be merged, I can write up either approach and do a PR.

**Comment by pfmoore** [comment]
I can't follow what is being proposed in the gerrit link, and I'm not entirely sure what you mean by using the appveyor GUI. I'd suggest you write up a PR to give us something concrete to discuss.

Personally, I'd be happy to see something like this included, as it lowers the barrier for people without access to Windows providing support for Windows users. Although I question the motivation for providing Windows builds without doing Windows CI (how will you respond to bug reports?) Appveyor's service is slow enough that there may be *other* good reasons for wanting to not add it to your testing, though, so that's not a showstopper.

Could you please ensure that the PR is worded in a more positive manner though - "despise having such junk in their repo" isn't the sort of tone we want to set. (I'm sure you intended to do so, just noting this as a general policy on how the PUG should treat Windows support).
