### ISSUE TITLE
Find better name for "non-src" layout

### ISSUE THREAD

**Issue by astrojuanlu** [pypa/packaging.python.org#618]
From https://github.com/pypa/packaging.python.org/issues/320#issuecomment-495990983:

> We should use a name for non-src/ layout that isn't negative-tone: 

Suggestions so far:

* flat
* natural
* root
* simple
* adhoc (https://github.com/pypa/packaging.python.org/issues/320#issuecomment-496006293)

**Comment by cjerdonek** [comment]
Another possibility:

* top-level

**Comment by drunkwcodes** [comment]
I think it should be just "src" layout and others.

The src layout seems to be misused and denies the fact that `setup.py` is kind of a piece of important source which runs on every installation.

**Comment by pradyunsg** [comment]
Since this is bikesheding after all, I think it is important to decide what to focus on.

I think that'll be: what these terms might communicate to first timers and to avoid names that can be mixed with other common concepts.

IMO that means we can take the following off the table:

- "root" can be confused with the root of the file system or as the superuser.
- "simple" and "natural" would communicate that the layout is somehow better than the alternatives. (we don't want to convey either way, in the guide)
- "adhoc" would communicate that the layout is inferior to the alternatives. (we don't want to convey either way, in the guide)

That leaves us with "flat" and "top-level".

Between these two, I think I'll go with flat since it's a common enough name and conveys the meaning well enough. It'll be pretty search friendly too.

**Comment by drunkwcodes** [comment]
No. "Flat" layout conflicts with its duplicate path name convention.
"Mediocre" layout for the first timers FTW.

**Comment by pradyunsg** [comment]
Not sure if you're serious or trying to be funny/sarcastic there.

Anyway, mediocre doesn't make sense (it's not a neutral term) so I'm going to ignore all of that.

**Comment by ncoghlan** [comment]
Directory name duplication happens in both layouts when the source project and the published package share a name (it just appears as `project/package` in the flat layout, and `project/src/package` in the src layout).

So the general way of describing the two layouts would be:

> In a flat project layout, the importable Python modules and/or packages live at the same level as the distribution package definition files (e.g. `pyproject.toml`, `setup.py`, `setup.cfg`, `MANIFEST.in`), whereas in a "src" (pronounced "source") layout, the importable components are placed one level further down, inside a `src` subdirectory.

**Comment by pradyunsg** [comment]
@ncoghlan I'm gonna borrow that wording, for the discussion topic. :)

**Comment by ibraheemybg** [comment]
Hello am actually an intermediate python developer but then i think "auto_src.py" will make a good layout as it will kind of notify users that its automatic and he no specific layout🙌🏼

**Comment by pradyunsg** [comment]
The concensus here seems to be "flat". :)
