### ISSUE TITLE
Two different URLS for packaging tutorial

### ISSUE THREAD

**Issue by blairg23** [pypa/packaging.python.org#636]
I can't tell if this is a bug or not, but I found two different URLs that led me to the "Python Packaging User Guide", which seem like identical pages...

Page 1: https://packaging.python.org/

Page 2: https://python-packaging-user-guide.readthedocs.io/

**Comment by ncoghlan** [comment]
Yep, that's expected - the first one goes through the PSF's CDN frontend (and is the preferred domain for external links to target), while the second is the actual documentation hosting on ReadTheDocs.

The GitHub repo and the ReadTheDocs project originally had the same name (before we set up the packaging.python.org subdomain), but we later changed the GitHub repo name to match the public CDN endpoint (since more folks will now recognise it by that name).
