### ISSUE TITLE
Autoinviting authors to review changes to the content they contributed

### ISSUE THREAD

**Issue by webknjaz** [pypa/packaging.python.org#680]
When somebody sends a PR, it's useful to ask the original author(s) of the given guide to review it. For this, maintainers need to find out who that is, using `git blame` or trying to recall this information. [`authors.txt`] is a bit out-of-date and also it doesn't map authors to their contents.

I suggest using `.github/CODEOWNERS` to track this information. This will make GitHub automatically request reviews from the corresponding users so no manual guessing is needed. This would require adding `CODEOWNERS` entries every time a new guide is added or a big change is made.

Refs:
* https://github.blog/2017-07-06-introducing-code-owners/
* https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-syntax

[`authors.txt`]:
https://github.com/pypa/packaging.python.org/blob/d98a7e4/authors.txt

**Comment by webknjaz** [comment]
For example, I'd like to be auto-pinged about things like https://github.com/pypa/packaging.python.org/pull/677.

**Comment by di** [comment]
I personally try to treat pending requested reviews as blocking, so I'd be hesitant to add this since it means that we'd need to wait for the original author to review before merging. However, I suppose if this starts happening we can always remove the mapping in `CODEOWNERS`.

I think this is probably fine if the people who want it do it themselves, and stay up-to-date with pending reviews. I don't think we should just add all authors to `CODEOWNERS`, I think this would probably just generate unnecessary noise (i.e. it should be opt-in).

**Comment by webknjaz** [comment]
Yes, I think I wanted suggest opt-in originally. But I think we may need a way to notify authors about such possibility.

**Comment by pradyunsg** [comment]
Merged #705 in the spirit of opt-in.
