### ISSUE TITLE
advice for maintainers on dropping universal=1 wheels

### ISSUE THREAD

**Issue by graingert** [pypa/packaging.python.org#726]
There should be some advice on what to do about universal wheels when dropping support for python versions in this guide: https://packaging.python.org/guides/dropping-older-python-versions/

eg, should this:
```
# setup.cfg
[bdist_wheel]
universal=1
```
 be removed?

**Comment by webknjaz** [comment]
Yes! It's a great idea! I keep having `universal=1` in some places because it never occured to me that it should be changed. Earlier today @gaborbernat pointed out to me that this is wrong and causes the wheels to be `py2.py3`. I somehow didn't realize this.

So I was about to file an issue about it when I found this one :)

The docs change should point out that the maintainers should be mindful of what their wheel tags are compared to what's written in the `Requires-Python` fields in metadata.

It also seems like a good idea to improve the linting side of the problem in the ecosystem: https://github.com/pypa/twine/issues/739.

P.S. I tested that projects having such metadata mismatches are harmless (if they don't have a hard conflict in that metadata) and pip seems to do the right thing but it's still a good idea to keep it in sync.

**Comment by hugovk** [comment]
Yep, comparing wheel filenames created with and without the flag:

```
pyflakes-2.2.0-py2.py3-none-any.whl
pyflakes-2.2.0-py3-none-any.whl
```

Their contents are identical, except for `pyflakes-2.2.0.dist-info/WHEEL` (and `RECORD`'s hash of this file):

```
Wheel-Version: 1.0
Generator: bdist_wheel (0.36.0)
Root-Is-Purelib: true
Tag: py2-none-any
Tag: py3-none-any
```
```
Wheel-Version: 1.0
Generator: bdist_wheel (0.36.0)
Root-Is-Purelib: true
Tag: py3-none-any
```
