### ISSUE TITLE
Missing documention for .pypirc format

### ISSUE THREAD

**Issue by stdedos** [pypa/packaging.python.org#730]
Would this be the correct place for this issue? https://github.com/pypa/twine/issues/638

> ```console
> u@h:~/pak$ twine upload .tox/dist/* -r test-pypi
> InvalidConfiguration: Missing 'test-pypi' section from the configuration file
> or not a complete URL in --repository-url.
> Maybe you have a out-dated '~/.pypirc' format?
> more info: https://docs.python.org/distutils/packageindex.html#pypirc
> 
> ```
> 
> Last v3 url that's valid is https://docs.python.org/3.6/distutils/packageindex.html#pypirc (and Google offers https://docs.python.org/3.3/distutils/packageindex.html#pypirc)

**Comment by bhrutledge** [comment]
(originally from https://github.com/pypa/twine/issues/638)

Thanks, @stdedos. It looks like that documentation was removed in https://github.com/python/cpython/pull/13087.

After looking around a bit, it seems like there is no current documentation of the `.pypirc` format. There are some examples at:

- [Packaging and distributing projects — Python Packaging User Guide](https://packaging.python.org/guides/distributing-packages-using-setuptools/?highlight=pypirc#create-an-account)
- [Migrating to PyPI.org — Python Packaging User Guide](https://packaging.python.org/guides/migrating-to-pypi-org/?highlight=pypirc)

But those aren't complete; for example, they don't document how to use a custom repository.

So, it seems like the format should be documented somewhere, but it's not clear to me where. Some relevant discussions:

- https://github.com/pypa/twine/pull/340/: A PR for documenting `.pypirc` in twine, which was closed with the suggestion of moving it to the [Python Packaging User Guide](https://packaging.python.org/)
- https://github.com/pypa/packaging.python.org/issues/297#issuecomment-576409783: A roundup I did of outstanding issues related to managing credentials with `.pypirc`

It seems to me that twine is the primary (and maybe only?) consumer of `.pypirc`, and that it's a frequent source of confusion, so my initial vote was to document the format in twine's docs, and link to it from the Packaging User Guide.

However, @sigmavirus24 suggested that the Packaging User Guide would be the right place because twine doesn't own or control the format. So, maybe document here, then update the twine error message and mention it in the docs?

It looks like @di might have the most context across projects.

**Comment by di** [comment]
I think we need to document/standardize the existing `.pypirc` format. It's unclear to me whether this needs to be a PEP or we can just do it in the specifications section of this guide.

**Comment by bhrutledge** [comment]
@di Would it be reasonable to start with a PR here that adds some combination/edit of the content removed from the `distutils` docs and https://github.com/pypa/twine/pull/340?

I could take a pass at that.

**Comment by di** [comment]
@bhrutledge I think that would be a reasonable first step.
