### ISSUE TITLE
Wrong if condition to establish if commit is tagged

### ISSUE THREAD

**Issue by guglielmosanchini** [pypa/packaging.python.org#742]
here, https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/, in the section: Publishing the distribution to PyPI and TestPyPI,
the line **if: startsWith(github.event.ref, 'refs/tags')** should be **if: startsWith(github.ref, 'refs/tags')**

**Comment by di** [comment]
Thanks! Looks like this was done in https://github.com/pypa/gh-action-pypi-publish/commit/55abf9c047d0a4a6b07b9318fec99297801871ba as well, so it seems valid. I've added a "good first issue" label here.

(cc @webknjaz)

**Comment by webknjaz** [comment]
Yeah, I guess that event structure changed over time. Honestly, I'm considering to switch it over to the `created` event instead according to pointers @ https://github.com/pypa/gh-action-pypi-publish/pull/31.
I'm currently battle-testing this approach in a few of my repos, in order to come up with a more robust example to recommend. And I'm yet to develop a more complex guide with OS-specific wheels and testing the dists before upload (that should be a separate tutorial, of course).

@guglielmosanchini if you feel like contributing, you could send a patch against https://github.com/pypa/packaging.python.org/blob/master/source/guides/github-actions-ci-cd-sample/publish-to-test-pypi.yml meanwhile — that's what shows up on the web-page.
