### ISSUE TITLE
packaging.python.org Windows commands

### ISSUE THREAD

**Issue by wackyblackie** [pypa/packaging.python.org#874]
In the Python Packaging User Guide the commands for Windows are ```py```. When I run them like that (with ```py```), I get:
```cmd
C:\>py --version
'py' is not recognized as an internal or external command,
operable program or batch file.
```
However, when I use the "Unix/macOS" commands, it works just fine:
```cmd
C:\>python3 --version
Python 3.8.8
```

Maybe consider switching the Windows commands to ```python3``` or take away the Windows-specific commands.

Best regards,
@wackyblackie

**Comment by pfmoore** [comment]
That looks like you have a version of Python that didn't come from the python.org installers. Where did you install Python from?

**Comment by wackyblackie** [comment]
I installed Python from the Microsoft Store.

**Comment by pradyunsg** [comment]
Cross linking to #863.

**Comment by zooba** [comment]
All the context is there - the Store package installs `python`/`python3`/`python3.x` commands, but not install `py` (because it couldn't override the python.org `py` and would just create more conflicts).

I posted on the other linked issue with my proposal, but to repeat it, "if `py` works for you, use that anywhere you see `python3`".

**Comment by pradyunsg** [comment]
Closing this since #863 covered this.
