### ISSUE TITLE
packaging exercise: pip does not install latest version

### ISSUE THREAD

**Issue by bryandenniskeith** [pypa/packaging.python.org#906]
I was following this packaging tutorial: https://packaging.python.org/tutorials/packaging-projects/
and had to make a number of changes to my project.  At each change I incremented the version number and uploaded the new version to testpypi.  I could see the new version on the server.  However, when I went to download and install the new version in my virtual environment, pip wouldn't install the new one.  For example, here's what I got when I wanted to install v 0.0.5:

```
(installation_test) /installation_test$ python3 -m pip install -vvv --index-url https://test.pypi.org/simple/ --no-deps example-pkg-bryankeith
...messages...
Requirement already satisfied: example-pkg-bryankeith in ./lib/python3.8/site-packages (0.0.4)
```
so

```
(installation_test) /installation_test$ rm -r ./lib/python3.8/site-packages/example_pkg_bryankeith-0.0.4.dist-info/
(installation_test) /installation_test$ python3 -m pip install -vvv --index-url https://test.pypi.org/simple/ --no-deps example-pkg-bryankeith
...lots of messages...
Successfully installed example-pkg-bryankeith-0.0.5
```
Is this the expected behavior?  I read that this was an old issue with pip, but my version is not old:

```
(installation_test) /installation_test$ python3 -m pip --version
pip 20.0.2 from /installation_test/lib/python3.8/site-packages/pip (python 3.8)
```

**Comment by webknjaz** [comment]
> However, when I went to download and install the new version in my virtual environment, pip wouldn't install the new one.

If you did that immediately after upload, you must've hit the cache. It gets invalidated in about 10 minutes. So normally, you shouldn't attempt installing right away because some parts of PyPI or its CDN might be not yet aware of the new release.

> (installation_test) /installation_test$ rm -r ./lib/python3.8/site-packages/example_pkg_bryankeith-0.0.4.dist-info/

Please, do not edit the contents of `site-packages` manually. Well, you _could_ do this in an isolated virtualenv for educational purposes, of course, but make sure to destroy it and recreate from scratch after you've played with its contents, for the sake of consistency. Instead, you could use `pip uninstall` which is able to correctly remove the dists.
Note that this command you ran drops the dist metadata but not the package contents. In fact, there are records in that metadata that track which files belong to the package. By removing it, you essentially make pip unaware of the existence of this package in site-packages and it wouldn't know which files belong to it.

Assuming you want to test installation and not the uploading process, you may use something like `pip install ./dist/example_pkg*.whl` to install from the artifact directly, without going through PyPI.

Also, if you want to inspect the dist contents — it's possible to just unarchive those artifacts in a temporary directory. sdists are usually tarballs (.tar.gz) so you could use `tar xzvf example_pkg*.tar.gz` and wheels are always zip archives. So use `unzip example_pkg*.whl` or `wheel unpack example_pkg*.whl` to get their contents. Inside, you'll find what actually gets packaged (a Python package or a module) along with some metadata folder (*.egg-info or *.dist-info) containing various bits of metadata.

**Comment by pfmoore** [comment]
```
(installation_test) /installation_test$ python3 -m pip install -vvv --index-url https://test.pypi.org/simple/ --no-deps example-pkg-bryankeith
...messages...
Requirement already satisfied: example-pkg-bryankeith in ./lib/python3.8/site-packages (0.0.4)
```

You didn't specify `--upgrade`, so pip sees 0.0.4 is installed, that satisfies the requirement to install the package, so it stops there.

**Comment by webknjaz** [comment]
Oh, that. I missed this line :man_facepalming:

**Comment by webknjaz** [comment]
And I want to add that `pip install example-pkg-bryankeith` means _I want **some** version of `example-pkg-bryankeith` to be present in my env_ while if you'd used `pip install 'example-pkg-bryankeith > 0.0.4'`, it'd tell pip to look for a newer version even without `--upgrade|-U` because the currently installed one wouldn't satisfy the install request.

**Comment by bryandenniskeith** [comment]
`--upgrade` is what I needed plus the advice of waiting a bit before trying to download and install the newly uploaded package.  Thank you for answering my pip questions and also for explaining quite clearly what is actually going on.  I had tried `--upgrade` at one point and unknowingly ran into the problem of hitting the server too quickly before the package was ready.  :)

**Comment by webknjaz** [comment]
I wonder if we need to add a note somewhere in the tutorial about the situation with the cache...

Do we have any other possible action items here?

**Comment by pradyunsg** [comment]
Doesn't look like there's any action items here.
